### ISSUE TITLE
Xtina's Issues

### ISSUE THREAD

**Issue by xtinarees** [dallasnews/dmn-vendor-wrapper#2]
* Looks like the wrapper is using the old styling for the footer that has an overlapping issue with the "Real Local Journalism" text and the copyright on mobile: 
![Screen Shot 2019-10-08 at 3 07 33 PM](https://user-images.githubusercontent.com/6852913/66429422-a104c780-e9dd-11e9-833e-8fec62eda6f4.png)

* This is using the larger DMN logo size that we use just on the homepage. It should be using the smaller logo size instead.

* The nav urls are all relative, I think they need to be absolute since the sites will possibly be on other domains / subdomains.

**Comment by nigelgilbert** [comment]
Thank you!  Very useful feedback.

> he nav urls are all relative, I think they need to be absolute since the sites will possibly be on other domains / subdomains.

😅 Good catch!!

**Comment by nigelgilbert** [comment]
@xtinarees I have addressed all issues!
